databases:
  - name: JobflexDB
    plan: free
    databaseName: jobflex_db
    user: jobflex

services:
  - type: web
    plan: free
    name: Jobflex
    runtime: python
    rootDir: ./Jobflex
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DEBUG
        value: 'FALSE'
      - key: DATABASE_URL
        fromDatabase:
          name: JobflexDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4