name: Download
on:
  workflow_dispatch:
jobs:
  google_drive_download:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire Google access token
        id: google-access-token
        uses: playeveryware/action-google-access-token@v1
        with:
          credentials: ${{ secrets.GIT_UPLOAD_CREDS }}
          scope: 'https://www.googleapis.com/auth/drive.readonly'

      - name: Download file
        uses: playeveryware/action-google-drive-download@v1
        with:
          token: ${{ steps.google-access-token.outputs.token }}
          file-url: 'https://drive.google.com/file/d/1awy6ufig25dGHLyPRaz_Fkd7c1930NS-/view?usp=sharing'
          path: Documentos

      - name: Show file information
        run: |
          ls Documentos
